# This is a working example of using GitHub Actions to publish the docs
# to the GitHub Pages (gh_pages) branch.
#
# Remember to have a requirements.txt file with the required dependencies.

name: Deploy Site

on:
  push:
    paths: 
    - 'docs/**'
    - 'mkdocs.yml'
    - 'theme/**'
    branches:
    - main
  workflow_dispatch:
  repository_dispatch:
    types:
      - trigger-from-notes

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      # added for timvink/mkdocs-git-revision-date-localized-plugin
      with:
        fetch-depth: 0
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -r requirements.txt
    - uses: actions/cache@v4
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-

    # checks out private notes repo
    - name: Checkout Private Notes Repository
      run: git clone https://${{ secrets.FINE_GRAINED_PAT_FOR_NOTES }}@github.com/dpi0/notes.git notes

   # copies all notes to the docs/ dir
    - name: Copy Private Notes to docs
      # run: rsync -av --exclude='.git' notes/ docs/
      # commented out .git for timvink/mkdocs-git-revision-date-localized-plugin to get the proper dates using git
      run: rsync -av notes/ docs/
      
      
    - name: Deploy Files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        mkdocs gh-deploy --force
